[pytest]
log_cli = 1
log_format = %(asctime)s %(levelname)s %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
log_cli_level = INFO
log_cli_format = %(asctime)s %(levelname)s %(message)s
log_cli_date_format=%Y-%m-%d %H:%M:%S


[testit]
url = https://team-tqq2.testit.software
private-token = Vkd5azFKVzFNdkR6cVRRbzNv
project-id = 019c7f42-4ec0-7dbb-b3dd-ced03f251761
configuration-id = 019c7f42-4ef7-74b9-82c9-3f71614cf79e
test-run-name = Pytest Automated Run


markers =
    smoke: быстрые тесты
    regression: регрессионные тесты
    slow: медленные тесты
    api: API-тесты
    very_slow: очень медленные тесты
    ui: ui тесты
    ui_movie: ui тесты на странице с фильмом
